A sample project
3.1
40086
40292
40086
40292
4
1.1
5
70
5.0
-6
20
1.0
3
1.0
12
30
0.3
1
12.0
28.0
3
-- 1. Climate (CLI) file
project.CLI
C:\FAO\AquaCrop\DATA\
1.1 Temperature (TMP) file
project.TMP
C:\FAO\AquaCrop\DATA\
1.2 Reference ET (ETo) file
project.ETO
C:\FAO\AquaCrop\DATA\
1.3 Rain (PLU) file
project.PLU
C:\FAO\AquaCrop\DATA\
1.4 Atmospheric CO2 (CO2) file
project.CO2
C:\FAO\AquaCrop\DATA\
-- 2. Crop (CRO) file
project.CRO
C:\FAO\AquaCrop\DATA\
-- 3. Irrigation (IRR) file
(None)
(None)
-- 4. Management (MAN) file
(None)
(None)
-- 5. Soil (SOL) file
project.SOL
C:\FAO\AquaCrop\DATA\
-- 6. Initial conditions (SW0) file
(None)
(None)
-- 7. Off-season conditions (OFF) file
(None)
(None)
